server:
  port: 8888
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/varshneyajay-act21/spring-cloud-server-config.git
          username: varshneya42@gmail.com
          password: 1200@Ajay